// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRDppXtMjHGapJ2KPt9Io7nTXvsQyMj-g',
    appId: '1:851994364654:web:6a4a73f8862d8adaba81ff',
    messagingSenderId: '851994364654',
    projectId: 'currency-converter-9d207',
    authDomain: 'currency-converter-9d207.firebaseapp.com',
    storageBucket: 'currency-converter-9d207.firebasestorage.app',
    measurementId: 'G-FW8EH9LDWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH_hODdv-InOuSb_Y2yTXK37-XsNf2H2Y',
    appId: '1:851994364654:android:4e1c1b402abd3db3ba81ff',
    messagingSenderId: '851994364654',
    projectId: 'currency-converter-9d207',
    storageBucket: 'currency-converter-9d207.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIsOfME51g19kkOg1Kz6qkhXoj7CiE0sg',
    appId: '1:851994364654:ios:8c1f52d7876533c8ba81ff',
    messagingSenderId: '851994364654',
    projectId: 'currency-converter-9d207',
    storageBucket: 'currency-converter-9d207.firebasestorage.app',
    iosBundleId: 'com.example.hawely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIsOfME51g19kkOg1Kz6qkhXoj7CiE0sg',
    appId: '1:851994364654:ios:8c1f52d7876533c8ba81ff',
    messagingSenderId: '851994364654',
    projectId: 'currency-converter-9d207',
    storageBucket: 'currency-converter-9d207.firebasestorage.app',
    iosBundleId: 'com.example.hawely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRDppXtMjHGapJ2KPt9Io7nTXvsQyMj-g',
    appId: '1:851994364654:web:b85730da0dca6bccba81ff',
    messagingSenderId: '851994364654',
    projectId: 'currency-converter-9d207',
    authDomain: 'currency-converter-9d207.firebaseapp.com',
    storageBucket: 'currency-converter-9d207.firebasestorage.app',
    measurementId: 'G-J3PD74ZWN5',
  );
}
